spring:
  server:
    port: 10000
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.131.131/personal
    username: web_user
    password: 1234

  # JPA Configuration
  #----------------------------------
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  # Thymeleaf Setting
#------------------------------------
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379
  # MultipartFile
#------------------------------------
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jwt:
  token:
    creator: poly
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'

api:
  gateway: localhost:13000