server:
  port: 11000
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.cbe4ia8uw1b6.ap-northeast-2.rds.amazonaws.com:3306/myDB
    username: poly
    password: poly01!
    hikari:
      maximum-pool-size: 10
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
  data:
    mongodb:
      uri: mongodb+srv://junsoo971230:pPsSA0MJOwcc4z6p@faceid.k9wruxl.mongodb.net/?retryWrites=true&w=majority&appName=FaceID
      database: MyDB
    redis:
      host: 3.36.189.222
      port: 6379
      username: poly
      password: 1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  mail:
    host: smtp.naver.com
    port: 465
    username: wnstn7759@naver.com
    password: wnstn@110214
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  token:
    expirationTime: 3600
    creator: poly
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'
univCert:
  api:
    key: '66197667-ef57-4bc8-a944-4815185c9e77'
cloud:
  aws:
    credentials:
      secret-key: EkImSQkHw4gnOz2s9AjCD37OWFL2T8YXvCy3YEbI
      access-key: ErASUUxnO1XYocc3pIJn
    s3:
      bucket: personalprj/senierPRJ
      endPoint: https://kr.object.ncloudstorage.com
    region:
      static: kr-standard
    stack:
      auto: 'false'
api:
  service:
    key: 'rtb38tc_tje2e3ojb98_e2cce922epbc'
