server:
  port: 10000
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.131.133/myDB
    username: poly
    password: 1234
  data:
    mongodb:
      uri: mongodb+srv://junsoo971230:pPsSA0MJOwcc4z6p@faceid.k9wruxl.mongodb.net/?retryWrites=true&w=majority&appName=FaceID
    #      host: 172.31.45.121
#      port: 27017
      database: MyDB
#      username: myUser
#      password: 1234

    redis:
      host: 192.168.131.133
      port: 6379
      username: poly
      password: 1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  mail:
    host: smtp.naver.com
    port: 465
    username: wnstn7759@naver.com
    password: wnstn@110214
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  # MultipartFile
  #------------------------------------
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA Configuration
  #----------------------------------

jwt:
  token:
    expirationTime: 3600
    creator: poly
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'

api:
  gateway: localhost:13000

univCert:
  api:
    key: '66197667-ef57-4bc8-a944-4815185c9e77'


# AWS S3 Setting
cloud:
  aws:
    credentials:
      secret-key: EkImSQkHw4gnOz2s9AjCD37OWFL2T8YXvCy3YEbI
      access-key: ErASUUxnO1XYocc3pIJn
    s3:
      bucket: personalprj/senierPRJ
      endPoint: https://kr.object.ncloudstorage.com
    region:
      static: kr-standard
    stack:
      auto: 'false'
