server:
  port: 10000
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.131.133/myDB
    username: poly
    password: 1234
  data:
    mongodb:
      host: 192.168.131.133
      database: MyDB
      port: 27017
      username: myUser
      password: 1234
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  # MultipartFile
  #------------------------------------
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # JPA Configuration
  #----------------------------------

jwt:
  token:
    expirationTime: 3600
    creator: poly
    refresh:
      valid:
        time: '3000'
      name: jwtRefreshToken
    access:
      valid:
        time: '300'
      name: jwtAccessToken
  secret:
    key: '12345678123456781234567812345678123456781234'

api:
  gateway: localhost:13000

univCert:
  api:
    key: '66197667-ef57-4bc8-a944-4815185c9e77'